apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      enfFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
